#!/bin/bash
first_name=("James" "Mary" "Robert" "Patricia" "John" "Jennifer" "Michael" "Linda" "William" "Elizabeth" "David" "Barbara" "Richard" "Susan" "Joseph" "Jessica" "Thomas" "Sarah" "Charles" "Karen" "Christopher" "Nancy" "Daniel" "Lisa" "Matthew" "Betty" "Anthony" "Margaret" "Mark" "Sandra" "Donald" "Ashley" "Steven" "Kimberly" "Paul" "Emily" "Andrew" "Donna" "Joshua" "Michelle" "Kenneth" "Dorothy" "Kevin" "Carol" "Brian" "Amanda" "George" "Melissa" "Edward" "Deborah" "Ronald" "Stephanie" "Timothy" "Rebecca" "Jason" "Sharon" "Jeffrey" "Laura" "Ryan" "Cynthia" "Jacob" "Kathleen" "Gary" "Amy" "Nicholas" "Shirley" "Eric" "Angela" "Jonathan" "Helen" "Stephen" "Anna" "Larry" "Brenda" "Justin" "Pamela" "Scott" "Nicole" "Brandon" "Emma" "Benjamin" "Samantha" "Samuel" "Katherine" "Gregory" "Christine" "Frank" "Debra" "Alexander" "Rachel" "Raymond" "Catherine" "Patrick" "Carolyn" "Jack" "Janet" "Dennis" "Ruth" "Jerry" "Maria" "Tyler" "Heather" "Aaron" "Diane" "Jose" "Virginia" "Adam" "Julie" "Henry" "Joyce" "Nathan" "Victoria" "Douglas" "Olivia" "Zachary" "Kelly" "Peter" "Christina" "Kyle" "Lauren" "Walter" "Joan" "Ethan" "Evelyn" "Jeremy" "Judith" "Harold" "Megan" "Keith" "Cheryl" "Christian" "Andrea" "Roger" "Hannah" "Noah" "Martha" "Gerald" "Jacqueline" "Carl" "Frances" "Terry" "Gloria" "Sean" "Ann" "Austin" "Teresa" "Arthur" "Kathryn" "Lawrence" "Sara" "Jesse" "Janice" "Dylan" "Jean" "Bryan" "Alice" "Joe" "Madison" "Jordan" "Doris" "Billy" "Abigail" "Bruce" "Julia" "Albert" "Judy" "Willie" "Grace" "Gabriel" "Denise" "Logan" "Amber" "Alan" "Marilyn" "Juan" "Beverly" "Wayne" "Danielle" "Roy" "Theresa" "Ralph" "Sophia" "Randy" "Marie" "Eugene" "Diana" "Vincent" "Brittany" "Russell" "Natalie" "Elijah" "Isabella" "Louis" "Charlotte" "Bobby" "Rose" "Philip" "Alexis" "Johnny" "Kayla")
last_name=("Smith" "Johnson" "Williams" "Brown" "Jones" "Garcia" "Miller" "Davis" "Rodriguez" "Martinez" "ernandez" "Lopez" "Gonzales" "Wilson" "Anderson" "Thomas" "Taylor" "Moore" "Jackson" "Martin" "Lee" "Perez" "Thompson" "White" "arris" "Sanchez" "Clark" "Ramirez" "Lewis" "Robinson" "Walker" "Young" "Allen" "King" "Wright" "Scott" "Torres" "Nguyen" "Hill" "Flores" "Green" "Adams" "Nelson" "Baker" "all" "Rivera" "Campbell" "Mitchell" "Carter" "Roberts" "Gomez" "Phillips" "Evans" "Turner" "Diaz" "Parker" "Cruz" "Edwards" "Collins" "Reyes" "Stewart" "Morris" "Morales" "Murphy" "Cook" "Rogers" "Gutierrez" "Ortiz" "Morgan" "Cooper" "Peterson" "Bailey" "Reed" "Kelly" "oward" "Ramos" "Kim" "Cox" "Ward" "Richardson" "Watson" "Brooks" "Chavez" "Wood" "James" "Bennet" "Gray" "Mendoza" "Ruiz" "ughes" "Price" "Alvarez" "Castillo" "Sanders" "Patel" "Myers" "Long" "Ross" "Foster" "Jimenez")
fav_color=("IndianRed" "LightCoral" "Salmon" "DarkSalmon" "LightSalmon" "Crimson" "Red" "FireBrick" "DarkRed" "Pink" "LightPink" "HotPink" "DeepPink" "MediumVioletRed" "PaleVioletRed" "LightSalmon" "Coral" "Tomato" "OrangeRed" "DarkOrange" "Orange" "Gold" "Yellow" "LightYellow" "LemonChiffon" "LightGoldenrodYellow" "PapayaWhip" "Moccasin" "PeachPuff" "PaleGoldenrod" "Khaki" "DarkKhaki" "Lavender" "Thistle" "Plum" "Violet" "Orchid" "Fuchsia" "Magenta" "MediumOrchid" "MediumPurple" "RebeccaPurple" "BlueViolet" "DarkViolet" "DarkOrchid" "DarkMagenta" "Purple" "Indigo" "SlateBlue" "DarkSlateBlue" "MediumSlateBlue" "GreenYellow" "Chartreuse" "LawnGreen" "Lime" "LimeGreen" "PaleGreen" "LightGreen" "MediumSpringGreen" "SpringGreen" "MediumSeaGreen" "SeaGreen" "ForestGreen" "Green" "DarkGreen" "YellowGreen" "OliveDrab" "Olive" "DarkOliveGreen" "MediumAquamarine" "DarkSeaGreen" "LightSeaGreen" "DarkCyan" "Teal" "Aqua" "Cyan" "LightCyan" "PaleTurquoise" "Aquamarine" "Turquoise" "MediumTurquoise" "DarkTurquoise" "CadetBlue" "SteelBlue" "LightSteelBlue" "PowderBlue" "LightBlue" "SkyBlue" "LightSkyBlue" "DeepSkyBlue" "DodgerBlue" "CornflowerBlue" "MediumSlateBlue" "RoyalBlue" "Blue" "MediumBlue" "DarkBlue" "Navy" "MidnightBlue" "Cornsilk" "BlanchedAlmond" "Bisque" "NavajoWhite" "Wheat" "BurlyWood" "Tan" "RosyBrown" "SandyBrown" "Goldenrod" "DarkGoldenrod" "Peru" "Chocolate" "SaddleBrown" "Sienna" "Brown" "Maroon" "White" "Snow" "HoneyDew" "MintCream" "Azure" "AliceBlue" "GhostWhite" "WhiteSmoke" "SeaShell" "Beige" "OldLace" "FloralWhite" "Ivory" "AntiqueWhite" "Linen" "LavenderBlush" "MistyRose" "Gainsboro" "LightGray" "Silver" "DarkGray" "Gray" "DimGray" "LightSlateGray" "SlateGray" "DarkSlateGray" "Black")

for i in $(seq 1 500); do 
    first_name_rand=$((1 + $RANDOM % ${#first_name[@]}))
    last_name_rand=$((1 + $RANDOM % ${#last_name[@]}))
    fav_color_rand=$((1 + $RANDOM % ${#fav_color[@]}))
    curl -X POST -d"{\"id\":$i,\"first_name\":\"${first_name[first_name_rand]}\",\"last_name\":\"${last_name[last_name_rand]}\",\"fav_color\":\"${fav_color[fav_color_rand]}\"}" localhost:8080/api/v1/users
done